"""extend tables

Revision ID: 8f61b7c1b580
Revises: a0753866b90e
Create Date: 2025-08-18 19:35:12.761393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f61b7c1b580'
down_revision: Union[str, Sequence[str], None] = 'a0753866b90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('user_gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('user_avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_weight', sa.DECIMAL(), nullable=True))
    op.add_column('users', sa.Column('user_height', sa.DECIMAL(), nullable=True))
    op.add_column('users', sa.Column('user_subscription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_subscription')
    op.drop_column('users', 'user_height')
    op.drop_column('users', 'user_weight')
    op.drop_column('users', 'user_avatar')
    op.drop_column('users', 'user_preferences')
    op.drop_column('users', 'user_birthday')
    op.drop_column('users', 'user_gender')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
